/*
@title: Spaceship Rescue
@author: Aditi Ranjan
*/

const player = "p";
const astronaut = "a";
const obstacle = "o";
const exit = "e";

setLegend(
  [player, bitmap`
................
................
.......000......
.....00CCC00....
......00000.....
......0...0.00..
....000C.C0.0...
....0.0...000...
...00.03330.....
.....00...0.....
.....0....0.....
.....00..00.....
......0000......
......0.0.......
.....CC.CC......
................`],
  [astronaut, bitmap`
................
................
.......222......
.......2.2......
......2..2......
......2...2.2...
....222.2.2.2...
....2.2...222...
....2.05552.....
......2...2.....
.....2....2.....
.....2...2......
......222.......
......2.2.......
.....22.22......
................`],
  [obstacle, bitmap`
................
................
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
....666666......
................
................
................`],
  [exit, bitmap`
................
................
.......333......
......3...3.....
.....3.....3....
....3.......3...
...3.........3..
...3.........3..
...3.........3..
....3.......3...
.....3.....3....
......3...3.....
.......333......
................
................
................`]
);

setSolids([player, obstacle]);

let level = 0;
const levels = [
  map`
p..............
......oo.......
......oo.......
..a.......a....
..oo....oo.....
..oo....oo.....
..a.......a....
....oo.........
....oo.........
....a.......a..
......oo.......
......oo.......
.....a......e..`
];

setMap(levels[level]);

setPushables({
  [player]: []
});

onInput("w", () => {
  getFirst(player).y -= 1;
});

onInput("a", () => {
  getFirst(player).x -= 1;
});

onInput("s", () => {
  getFirst(player).y += 1;
});

onInput("d", () => {
  getFirst(player).x += 1;
});

afterInput(() => {
  // Check if player reaches an spaceship
  getAll(astronaut).forEach(a => {
    if (getFirst(player).x === a.x && getFirst(player).y === a.y) {
      a.remove();
    }
    
  });

  // Check if player reaches the exit
  if (getFirst(player).x === getFirst(exit).x && getFirst(player).y === getFirst(exit).y) {
    addText("You Win!", { x: 8, y: 4, color: color`2` });
  }

  // Check if all spaceships are rescued
  if (getAll(astronaut).length === 0) {
    addText("All Rescued!", { x: 8, y: 4, color: color`2` });
  }
  
});
